config/routes.rb
Tracker::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1 do
      resources :products
      resources :prices
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products

  match '/login',             to: 'sessions#new',         via: 'get'
  match '/logout',            to: 'sessions#destroy',     via: 'delete'
  

  root 'sessions#new'

  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav">
          <% if logged_in? %>
            <li><%= link_to "Home/Users", current_user %></li>
            <li class="<%= 'active' if current_page?(logout_path) %>"><%= link_to("Logout", logout_path, method: "delete") %></li>
          <% else %>
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Login", root_path %></li>
          <% end %>
          <li class="<%= 'active' if current_page?(products_path) %>"><%= link_to("Products", products_path) %></li>
        </ul>
      <nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render("layouts/header") %>

  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <ul>
      <% if value.respond_to?('each') %>
        <% value.each do |m| %>
          <li><%= m %></li>
        <% end %>
      <% else %>
        <li><%= value %></li>
      <% end %>
    </div>
    <% end %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>

  </div>
</body>
</html>